#CI name
name: Nasa project CI
#Event
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
#Jobs
jobs:
  build:
    env: 
      CI: true
      MONGO_URL: mongo://localhost/nasa 
    strategy:
      matrix: 
        node-version: [14.x, 16.x]
        mongodb-version: ['6.0']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: mongoDB Action
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm run test